# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dei\Documents\Programming\Ranil_project_py\Screens\MainMenuScreens\Reports\User_Logs.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"background-color: #F8F8F0;\n"
"}\n"
"#Log_Table{\n"
"border : 2px solid #ABE27D;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(24)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Log_Table = QtWidgets.QTableWidget(self.widget)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        self.Log_Table.setFont(font)
        self.Log_Table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Log_Table.setAlternatingRowColors(True)
        self.Log_Table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Log_Table.setObjectName("Log_Table")
        self.Log_Table.setColumnCount(5)
        self.Log_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setBold(True)
        item.setFont(font)
        self.Log_Table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setBold(True)
        item.setFont(font)
        self.Log_Table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setBold(True)
        item.setFont(font)
        self.Log_Table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setBold(True)
        item.setFont(font)
        self.Log_Table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setBold(True)
        item.setFont(font)
        self.Log_Table.setHorizontalHeaderItem(4, item)
        self.Log_Table.horizontalHeader().setCascadingSectionResizes(True)
        self.Log_Table.horizontalHeader().setSortIndicatorShown(True)
        self.Log_Table.horizontalHeader().setStretchLastSection(True)
        self.Log_Table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.Log_Table)
        self.horizontalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ACTIVITY LOGS"))
        self.Log_Table.setSortingEnabled(True)
        item = self.Log_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "User ID"))
        item = self.Log_Table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "User Level"))
        item = self.Log_Table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "User"))
        item = self.Log_Table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Activity"))
        item = self.Log_Table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date / Time"))
