# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dei\Documents\Programming\Ranil_projecy_py\Screens\MainMenuScreens\Registration\Registration_prod.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 561)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(12)
        font.setBold(True)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{background-color: rgb(255, 255, 255);}\n"
"\n"
".QLabel{\n"
"    font: 700 12pt \"DM Sans\";\n"
"}\n"
"\n"
".QComboBox , .QLineEdit{\n"
"    font: 700 9pt \"Open Sans\";\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_9 = QtWidgets.QWidget(self.centralwidget)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout_7.addWidget(self.widget_9)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem)
        self.widget_10 = QtWidgets.QWidget(self.centralwidget)
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.widget = QtWidgets.QWidget(self.widget_10)
        self.widget.setStyleSheet("#widget{\n"
"background-color: #F8F8F0;\n"
"border: 2px solid #096033;\n"
"}\n"
".QComboBox\n"
"{\n"
"border : 2px solid #096033;\n"
"background-color:rgba(0,0,0,0);\n"
"}\n"
".QLineEdit{\n"
"border : 2px solid #096033;\n"
"background-color:rgba(0,0,0,0);\n"
"}\n"
".QDateEdit{\n"
"border: 2px solid #096033;\n"
"background-color:rgba(0,0,0,0);\n"
"}\n"
".QPushButton{\n"
"background-color: #096033;\n"
"color: white;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("#widget_2{\n"
"background-color: #ABE27D;\n"
"border: 2px solid #096033;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:rgba(0,0,0,0);")
        self.label.setIndent(10)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_8 = QtWidgets.QWidget(self.widget)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_5.setContentsMargins(25, -1, 25, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_7 = QtWidgets.QWidget(self.widget_8)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_7)
        self.widget_4.setStyleSheet(".QComboBox\n"
"{\n"
"border : 2px solid #096033;\n"
"}\n"
".QLineEdit{\n"
"border : 2px solid #096033;\n"
"}\n"
".QDateEdit{\n"
"border: 2px solid #096033;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.PName_LE = QtWidgets.QLineEdit(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PName_LE.sizePolicy().hasHeightForWidth())
        self.PName_LE.setSizePolicy(sizePolicy)
        self.PName_LE.setMinimumSize(QtCore.QSize(25, 35))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.PName_LE.setFont(font)
        self.PName_LE.setText("")
        self.PName_LE.setObjectName("PName_LE")
        self.verticalLayout_2.addWidget(self.PName_LE)
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.SPrice_LE = QtWidgets.QLineEdit(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SPrice_LE.sizePolicy().hasHeightForWidth())
        self.SPrice_LE.setSizePolicy(sizePolicy)
        self.SPrice_LE.setMinimumSize(QtCore.QSize(25, 35))
        self.SPrice_LE.setText("")
        self.SPrice_LE.setObjectName("SPrice_LE")
        self.verticalLayout_2.addWidget(self.SPrice_LE)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.widget_7)
        self.widget_3.setStyleSheet(".QComboBox\n"
"{\n"
"border : 2px solid #096033;\n"
"}\n"
".QLineEdit{\n"
"border : 2px solid #096033;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.UType_CB = QtWidgets.QComboBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UType_CB.sizePolicy().hasHeightForWidth())
        self.UType_CB.setSizePolicy(sizePolicy)
        self.UType_CB.setMinimumSize(QtCore.QSize(25, 35))
        self.UType_CB.setObjectName("UType_CB")
        self.verticalLayout.addWidget(self.UType_CB)
        self.label_6 = QtWidgets.QLabel(self.widget_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.CType_CB = QtWidgets.QComboBox(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CType_CB.sizePolicy().hasHeightForWidth())
        self.CType_CB.setSizePolicy(sizePolicy)
        self.CType_CB.setMinimumSize(QtCore.QSize(25, 35))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        self.CType_CB.setFont(font)
        self.CType_CB.setFrame(True)
        self.CType_CB.setObjectName("CType_CB")
        self.verticalLayout.addWidget(self.CType_CB)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.verticalLayout_5.addWidget(self.widget_7)
        self.widget_5 = QtWidgets.QWidget(self.widget_8)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_8.addWidget(self.label_5)
        self.desc_LE = QtWidgets.QLineEdit(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc_LE.sizePolicy().hasHeightForWidth())
        self.desc_LE.setSizePolicy(sizePolicy)
        self.desc_LE.setMinimumSize(QtCore.QSize(25, 35))
        self.desc_LE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.desc_LE.setClearButtonEnabled(False)
        self.desc_LE.setObjectName("desc_LE")
        self.verticalLayout_8.addWidget(self.desc_LE)
        self.verticalLayout_5.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.widget_8)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_btn = QtWidgets.QPushButton(self.widget_6)
        self.back_btn.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(12)
        font.setBold(True)
        self.back_btn.setFont(font)
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        spacerItem2 = QtWidgets.QSpacerItem(430, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.reg_btn = QtWidgets.QPushButton(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reg_btn.sizePolicy().hasHeightForWidth())
        self.reg_btn.setSizePolicy(sizePolicy)
        self.reg_btn.setMinimumSize(QtCore.QSize(125, 35))
        font = QtGui.QFont()
        font.setFamily("DM Sans")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.reg_btn.setFont(font)
        self.reg_btn.setObjectName("reg_btn")
        self.horizontalLayout.addWidget(self.reg_btn)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.verticalLayout_3.addWidget(self.widget_8)
        self.horizontalLayout_4.addWidget(self.widget)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_7.addWidget(self.widget_10)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "REGISTER PRODUCT"))
        self.label.setText(_translate("MainWindow", "REGISTER"))
        self.label_3.setText(_translate("MainWindow", "PRODUCT NAME:"))
        self.PName_LE.setPlaceholderText(_translate("MainWindow", "Ex: Dog Food(Beef & Veg)"))
        self.label_4.setText(_translate("MainWindow", "SELLING PRICE:"))
        self.SPrice_LE.setPlaceholderText(_translate("MainWindow", "Ex: 250"))
        self.label_8.setText(_translate("MainWindow", "UNIT TYPE:"))
        self.UType_CB.setPlaceholderText(_translate("MainWindow", "UNDEFINED"))
        self.label_6.setText(_translate("MainWindow", "CATEGORY:"))
        self.CType_CB.setPlaceholderText(_translate("MainWindow", "Ex: Dog Food"))
        self.label_5.setText(_translate("MainWindow", "DESCRIPTION:"))
        self.desc_LE.setPlaceholderText(_translate("MainWindow", "A food for Dogs."))
        self.back_btn.setText(_translate("MainWindow", "BACK"))
        self.reg_btn.setText(_translate("MainWindow", "REGISTER"))
