# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dei\Documents\Programming\Ranil_projecy_py\Screens\MainMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 567)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    var w = window.innerWidth;\n"
"    var h = window.innerHeight;\n"
"    print(w)\n"
"    print(h)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#sidebar{\n"
"background-color: black;\n"
"border: 0px solid white;\n"
"background: palette(base);\n"
"gridline-color: rgb(255, 255, 255);\n"
"    border-color: rgb(255, 255, 255);\n"
"    border-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"/*Nav Bar*/\n"
"\n"
"#top_bar{\n"
"    background-color: green;\n"
"}\n"
"\n"
"#menu_btn{\n"
"    border: 2px solid green;\n"
"    text-align: left;\n"
"    padding-left: 15px;\n"
"    background-color: green;\n"
"}\n"
"#menu_btn:checked, #menu_btn:toggled{\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* Side Buttons */ \n"
"#about_sdbtn, #help_sdbtn ,#inventory_sdbtn, #maintenance_sdbtn, #records_sdbtn,#registration_sdbtn,#reports_sdbtn,#sales_sdbtn,#security_sdbtn,#transaction_sdbtn{\n"
"    color: green;\n"
"    border: 3px solid green;\n"
"    text-align: left;\n"
"    padding: 10px 10px;\n"
"    background-color: white;\n"
"    margin: 0px;\n"
"    font-family: Roboto;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"}\n"
"#about_sdbtn:hover, #help_sdbtn:hover ,#inventory_sdbtn:hover, #maintenance_sdbtn:hover, #records_sdbtn:hover,#registration_sdbtn:hover,#reports_sdbtn:hover,#sales_sdbtn:hover,#security_sdbtn:hover,#transaction_sdbtn:hover {\n"
"    background-color: green;\n"
"    color: white;\n"
"}\n"
"#about_sdbtn:checked, #help_sdbtn:checked,#inventory_sdbtn:checked, #maintenance_sdbtn:checked, #records_sdbtn:checked,#registration_sdbtn:checked,#reports_sdbtn:checked,#sales_sdbtn:checked,#security_sdbtn:checked,#transaction_sdbtn:checked {\n"
"    background-color: green;\n"
"    color: white;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_bar = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_bar.sizePolicy().hasHeightForWidth())
        self.top_bar.setSizePolicy(sizePolicy)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 65))
        self.top_bar.setStyleSheet("")
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menu_btn = QtWidgets.QPushButton(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_btn.sizePolicy().hasHeightForWidth())
        self.menu_btn.setSizePolicy(sizePolicy)
        self.menu_btn.setMinimumSize(QtCore.QSize(60, 25))
        self.menu_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menu_btn.setStyleSheet("")
        self.menu_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/option white.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/Icons/Icons/option green.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.menu_btn.setIcon(icon)
        self.menu_btn.setIconSize(QtCore.QSize(25, 25))
        self.menu_btn.setCheckable(True)
        self.menu_btn.setChecked(False)
        self.menu_btn.setAutoExclusive(False)
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout_2.addWidget(self.menu_btn)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.nav_text = QtWidgets.QLabel(self.top_bar)
        self.nav_text.setStyleSheet("QLabel {\n"
"    font-family: Roboto;\n"
"    font-weight: bold;\n"
"    font-size: 15px;\n"
"    color: white;\n"
"}")
        self.nav_text.setObjectName("nav_text")
        self.horizontalLayout_2.addWidget(self.nav_text)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.RANIL_logo = QtWidgets.QLabel(self.top_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RANIL_logo.sizePolicy().hasHeightForWidth())
        self.RANIL_logo.setSizePolicy(sizePolicy)
        self.RANIL_logo.setMaximumSize(QtCore.QSize(65, 65))
        self.RANIL_logo.setText("")
        self.RANIL_logo.setPixmap(QtGui.QPixmap(":/Images/images/background.png"))
        self.RANIL_logo.setScaledContents(True)
        self.RANIL_logo.setObjectName("RANIL_logo")
        self.horizontalLayout_2.addWidget(self.RANIL_logo)
        self.verticalLayout_2.addWidget(self.top_bar)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setKerning(False)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.sideBar = QtWidgets.QWidget()
        self.sideBar.setGeometry(QtCore.QRect(0, 0, 123, 510))
        self.sideBar.setProperty("setVisible", False)
        self.sideBar.setObjectName("sideBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sideBar)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.security_sdbtn = QtWidgets.QPushButton(self.sideBar)
        self.security_sdbtn.setCheckable(True)
        self.security_sdbtn.setAutoExclusive(True)
        self.security_sdbtn.setObjectName("security_sdbtn")
        self.verticalLayout.addWidget(self.security_sdbtn)
        self.registration_sdbtn = QtWidgets.QPushButton(self.sideBar)
        self.registration_sdbtn.setCheckable(True)
        self.registration_sdbtn.setAutoExclusive(True)
        self.registration_sdbtn.setObjectName("registration_sdbtn")
        self.verticalLayout.addWidget(self.registration_sdbtn)
        self.sales_sdbtn = QtWidgets.QPushButton(self.sideBar)
        self.sales_sdbtn.setCheckable(True)
        self.sales_sdbtn.setAutoExclusive(True)
        self.sales_sdbtn.setObjectName("sales_sdbtn")
        self.verticalLayout.addWidget(self.sales_sdbtn)
        self.transaction_sdbtn = QtWidgets.QPushButton(self.sideBar)
        self.transaction_sdbtn.setCheckable(True)
        self.transaction_sdbtn.setAutoExclusive(True)
        self.transaction_sdbtn.setObjectName("transaction_sdbtn")
        self.verticalLayout.addWidget(self.transaction_sdbtn)
        self.inventory_sdbtn = QtWidgets.QPushButton(self.sideBar)
        self.inventory_sdbtn.setCheckable(True)
        self.inventory_sdbtn.setAutoExclusive(True)
        self.inventory_sdbtn.setObjectName("inventory_sdbtn")
        self.verticalLayout.addWidget(self.inventory_sdbtn)
        self.records_sdbtn = QtWidgets.QPushButton(self.sideBar)
        self.records_sdbtn.setCheckable(True)
        self.records_sdbtn.setAutoExclusive(True)
        self.records_sdbtn.setObjectName("records_sdbtn")
        self.verticalLayout.addWidget(self.records_sdbtn)
        self.reports_sdbtn = QtWidgets.QPushButton(self.sideBar)
        self.reports_sdbtn.setCheckable(True)
        self.reports_sdbtn.setAutoExclusive(True)
        self.reports_sdbtn.setObjectName("reports_sdbtn")
        self.verticalLayout.addWidget(self.reports_sdbtn)
        self.help_sdbtn = QtWidgets.QPushButton(self.sideBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help_sdbtn.sizePolicy().hasHeightForWidth())
        self.help_sdbtn.setSizePolicy(sizePolicy)
        self.help_sdbtn.setCheckable(True)
        self.help_sdbtn.setAutoExclusive(True)
        self.help_sdbtn.setObjectName("help_sdbtn")
        self.verticalLayout.addWidget(self.help_sdbtn)
        self.maintenance_sdbtn = QtWidgets.QPushButton(self.sideBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maintenance_sdbtn.sizePolicy().hasHeightForWidth())
        self.maintenance_sdbtn.setSizePolicy(sizePolicy)
        self.maintenance_sdbtn.setCheckable(True)
        self.maintenance_sdbtn.setAutoExclusive(True)
        self.maintenance_sdbtn.setObjectName("maintenance_sdbtn")
        self.verticalLayout.addWidget(self.maintenance_sdbtn)
        self.about_sdbtn = QtWidgets.QPushButton(self.sideBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.about_sdbtn.sizePolicy().hasHeightForWidth())
        self.about_sdbtn.setSizePolicy(sizePolicy)
        self.about_sdbtn.setCheckable(True)
        self.about_sdbtn.setAutoExclusive(True)
        self.about_sdbtn.setObjectName("about_sdbtn")
        self.verticalLayout.addWidget(self.about_sdbtn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.scrollArea.setWidget(self.sideBar)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_2)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nav_text.setText(_translate("MainWindow", "Ranil\'s Poultry Shop"))
        self.security_sdbtn.setText(_translate("MainWindow", "Security"))
        self.registration_sdbtn.setText(_translate("MainWindow", "Registration"))
        self.sales_sdbtn.setText(_translate("MainWindow", "Sales"))
        self.transaction_sdbtn.setText(_translate("MainWindow", "Transaction"))
        self.inventory_sdbtn.setText(_translate("MainWindow", "Inventory"))
        self.records_sdbtn.setText(_translate("MainWindow", "Records"))
        self.reports_sdbtn.setText(_translate("MainWindow", "Reports"))
        self.help_sdbtn.setText(_translate("MainWindow", "Help"))
        self.maintenance_sdbtn.setText(_translate("MainWindow", "Maintenance"))
        self.about_sdbtn.setText(_translate("MainWindow", "About"))
import assets.All_In_Resource_rc
